# Generated by Django 6.0 on 2025-12-11 05:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Дата рождения'),
        ),
    ]
